cosmos-installer: 
    form:
      - name: "name"
        label: "What do you want to call this server?"
        initialValue: "Palworld-Server"
        type: "text"
      - name: "password"
        label: "What Password do you want for the server?"
        initialValue: "Password"
        type: "text"
      - name: "adminpassword"
        label: "What Password do you want for the admin?"
        initialValue: "Password"
        type: "text"
      - name: community
        label: Public or Private? (true,false)
        initialValue: "false"
        type: select
        options:
          - - "true"
            - Yes
          - - "false"
            - No
      - name: players
        label: How many people can join this server? (Max 32)
        initialValue: 16
        type: text
      - name: "description"
        label: "How would you describe the server?"
        initialValue: "MOHAWK DINOSAUR"
        type: "text"
      - type: warning
        label: "As it is impossible to include all the configuration options in the
        installer, you can check the docs for more information on how to
        configure your server:
        https://github.com/thijsvanloef/palworld-server-docker"
      - type: warning
        label:"You must open UDP PORT 8211 for Gameplay, and UDP PORT 27015 to show up in the community server tab"
name: Palworld-Server
services:
  "{ServiceName}":
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp #Game Port
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
    environment:
      PORT: 8211  # Optional but recommended
      PLAYERS: {Context.players}  # Optional but recommended
      SERVER_PASSWORD: "{Context.password}"  # Optional but recommended
      MULTITHREADING: true
      RCON_ENABLED: true
      RCON_PORT: 25575
      TZ: Auto
      ADMIN_PASSWORD: "{Context.adminpassword}"
      COMMUNITY: {Context.community}  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      SERVER_NAME: "{Context.name}"
      SERVER_DESCRIPTION: "{Context.description}"
      volumes:
        type: volume
        source: "{ServiceName}-data"
        target: /palworld/
      labels:
        cosmos-force-network-secured: true
        cosmos-auto-update: true
        cosmos-icon: https://lilkidsuave.github.io/asteroidsinthecosmos/Palworld-Server/icon.png