name: Deploy static content to Pages

on:
  push:
    branches: ["master", "unstable"] 

  workflow_dispatch:

permissions:
  contents: read
  pages: write  
  id-token: write 

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Checkout unstable
        uses: actions/checkout@v7
        with:
          ref: unstable
          path: unstable
          clean: false

      - name: Remove .git from unstable
        run: rm -rf unstable/.git

      - name: Find and Replace unstable base URL
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "unstable/**"
          find: "https://azukaar.github.io/cosmos-servapps-official/"
          replace: "https://azukaar.github.io/cosmos-servapps-official/unstable/"
          regex: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Build static files
        run: node index.js && cd unstable && node index.js

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
